name: CI Pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout specific directory
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
        path: historical_data_collectors  # Check out only this directory

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Adjust the Python version as needed

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Adjust the path to your requirements file
      working-directory: historical_data_collectors

    - name: Run unit tests
      run: |
        pytest -v #
      working-directory: historical_data_collectors
